version: "3"
services:
  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: sh -c 'coverage run -m tests.tests_entry discover /app/tests && coverage report'
    depends_on:
      - postgres
    environment:
      - DB_URL
      - DB_NAME

  postgres:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
